### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by maartensandbox** [qcscine/autocas#5]
I'm trying to use autocas as-is, out of the box. This is my xyz file
[oxo_mult6.xyz.zip](https://github.com/qcscine/autocas/files/11871534/oxo_mult6.xyz.zip)

and I tried two different basis sets:
```
python3 -m scine_autocas --xyz_file oxo_mult6.xyz --basis_set sto-3g
python3 -m scine_autocas --xyz_file oxo_mult6.xyz --basis_set 6-31g
```

the first fails with

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/__main__.py", line 43, in <module>
    main_class.main(args)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/main_functions.py", line 470, in main
    final_occupation, final_orbital_indices = self.conventional(autocas, interface)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/main_functions.py", line 334, in conventional
    energy, initial_s1, initial_s2, initial_mutual_information = interface.calculate(
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/interfaces/molcas/__init__.py", line 569, in calculate
    self.hdf5_utils.modify_hdf5(self.orbital_file, cas_indices)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/interfaces/molcas/molcas_hdf5_utils.py", line 133, in modify_hdf5
    type_indices[i] = "2"
IndexError: index 172 is out of bounds for axis 0 with size 172

```

the second with

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/__main__.py", line 43, in <module>
    main_class.main(args)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/main_functions.py", line 470, in main
    final_occupation, final_orbital_indices = self.conventional(autocas, interface)
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/main_functions.py", line 348, in conventional
    final_occupation, final_orbital_indices = autocas.get_active_space(
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/__init__.py", line 310, in get_active_space
    if self.diagnostics.is_single_reference() and not force_cas:
  File "/home/maarten_vandamme/.local/lib/python3.9/site-packages/scine_autocas/autocas_utils/diagnostics.py", line 116, in is_single_reference
    if max(self.s1_entropy) < self.single_reference_threshold:
ValueError: max() arg is an empty sequence
```

Is something wrong with the way I invoke autcas, or is my input file a subtle cornercase? (for example it has nonzero total spin)

Another question - is there an example where I can use custom basis sets (let's say I want to use cc-pvdz extended with a few extra exponents for nitrogen, and sto-3g for the hydrogen atoms)?

**Comment by mmoerchen** [comment]
In the first case, looks like it might be the case, that AutoCAS does not identify the spin correctly.

Did you try to give it an "input.yml" instead of running it with arguments from the command line? Then you have a lot more options available. You can find an example input in the "scripts" directory.

Unfortunately, functions to customize basis sets are not implemented yet.
However, AutoCAS sets up the calculations, so you could a custom workflow, where your interface allows custom basis sets.

**Comment by mmoerchen** [comment]
Sorry for the late reply.
This error usually means, that the calculation did not run or crashed, so that no valid HDF5 file exists.

In order to use a different charge or spin you have to set it in the input file, which are set to 1 in your case.
