### ISSUE TITLE
no idea about how to run autocas correctly

### ISSUE THREAD

**Issue by histhinking** [qcscine/autocas#6]
Hi there,

I submitted the autocas job using a slurm script and the output suggests the autocas had been initiated.
But then something wrong just happend and killed the job. The standard error file reads:

Traceback (most recent call last):
  File "/home/$USER/.conda/envs/test/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/$USER/.conda/envs/test/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/scine_autocas/__main__.py", line 43, in <module>
    main_class.main(args)
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/scine_autocas/main_functions.py", line 428, in main
    interface.calculate()
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/scine_autocas/interfaces/molcas/__init__.py", line 547, in calculate
    self.run_initial_orbitals()
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/scine_autocas/interfaces/molcas/__init__.py", line 487, in run_initial_orbitals
    self.hdf5_utils.read_hdf5(self.orbital_file)
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/scine_autocas/interfaces/molcas/molcas_hdf5_utils.py", line 147, in read_hdf5
    h5_file = h5py.File(hdf5_file, "r")
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/$USER/.conda/envs/test/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/gpfs/home/$USER/molcas_test/autocas_project/initial/autocas_project.scf.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In the job script, I set

export OMP_NUM_THREADS=40
export MOLCAS=/home/$USER/softwares/OpenMolcas-v23.10/build
export MOLCAS_NPROCS=40
export MOLCAS_MEM=8GB
export MOLCAS_WORKDIR=/home/$USER/scratch/$SLURM_JOBID

It created two directories in the current directory, which are
"molcas_scratch" and "autocas_project"

Could anyone help me out? 

Thanks.

**Comment by weymutht** [comment]
Thanks for giving autoCAS a try! As you can see, the file `/gpfs/home/$USER/molcas_test/autocas_project/initial/autocas_project.scf.h5`. Two things come to my mind:

1. Are you sure that the environment variable `$USER` is properly resolved?
2. There might be a problem with the Molcas calculation. Check out the files in `/gpfs/home/$USER/molcas_test/autocas_project/initial` to investigate further.

**Comment by histhinking** [comment]
To whom it may concern,

      Thank you for your reply.

      Sorry for not getting back to you timely.

      I found out the reason of failure later, which is the default basis set does not support iodine. After switching to def2-tzvp, it worked.
 But my molecule containing 98 atoms and one Cu4I4 fragment may be too large for the Molcas so that it could not finish within a week.
How is the OpenMP parallelization efficiency of the program?

      Thanks,

       Guozhen

________________________________

**Comment by histhinking** [comment]
> Please note that we do not develop OpenMolcas, so we cannot really provide any support for this program.
> 
> As far as I know, OpenMolcas is mostly parallelized with OpenMPI, not OpenMP. I think enabling only OpenMP is limited to the linear algebra subroutines. However, I don't know how much faster this will make the calculations.

Thanks. As mentioned in another post, the DMRG part used OpenMP for parallelization. So for AutoCAS runs, should I use OpenMP?

**Comment by weymutht** [comment]
For QCMaquis, using OpenMP makes a lot of sense, yes :smiley:
